### ISSUE TITLE
How can I load multiple instance of this driver?

### ISSUE THREAD

**Issue by vicary** [adrianomarto/soft_uart#2]
I want to enable multiple pairs of GPIO as UART, running in a very low baud rate (i.e. <1200).

According to this link https://pinout.xyz/pinout/1_wire one can theoretically load multiple instance under different parameters, does this module support this kind of loading?

**Comment by adrianomarto** [comment]
Hi Vicary,
This module has not been designed to be loaded multiple times. But you could modify it to make it possible.  You might want to take a look at this:
http://codeintherightway.blogspot.com/2017/09/soft-uart-implementation-for-raspberry.html?showComment=1517897799896#c5449776426724801132
Kind regards,
Adriano.

**Comment by vicary** [comment]
Thank you!
