### ISSUE TITLE
Is it possible to have several of these devices concurrently?

### ISSUE THREAD

**Issue by daniel-dlds** [adrianomarto/soft_uart#22]
Hi, 
Great idea you had. I'ts just what I need. I have an application that needs two Serial ports. I can go with the one on the Pi and use your software for the other, the app is not required to go beyond 4800 baud,
Is there a possibility of supporting two sets of GPIO pins with this ? or only one is allowed ?
Thanks,
Regards

**Comment by adrianomarto** [comment]
Hi. The software currently supports only one software-implemented UART. Using one existing hardware-implemented plus one software-implemented should work though. Cheers!
